builds:
  - id: wdbcli
    main: cmd/wdbcli/cli.go
    binary: wdbcli
    goos: [ windows, darwin, linux]
    goarch: [ amd64, arm, arm64 ]
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    env:
      - CGO_ENABLED=0

archives:
  - id: wdbcli
    builds: [ wdbcli ]
    format: tar.gz
    files:
      - README.md
      # - CHANGELOG.md
      - LICENSE
dist: target/dist
release:
  github:
    owner: TanmoySG
    name: wunderDB
  prerelease: auto
  disable: false