# docker-compose for source (repo) container build
version: '3.4'

services:
  wunderdb:
    image: wunderdb
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: wunderdb
    ports:
      - 8086:8086
    environment:
      - PORT=8086
      - PERSISTANT_STORAGE_PATH=/wfs
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      # optional wdb-tools usage field - pass without quotes ("")
      - USE_TOOL=false
      - TOOL_INSTRUCTION=/tools/roles_hidden_field_update -f /wfs/roles/roles_persisted.json true
    volumes:
      - ./local_wdb/wfs:/wfs
      - ./local_wdb/txlogs:/root/wdb/txlogs
      - ./local_wdb/configs:/root/wdb/configs
