version: '3.4'

services:
  wunderdb:
    image: ghcr.io/tanmoysg/wunderdb:latest
    container_name: wunderdb
    ports:
      - 8086:8086
    environment:
      - PORT=8086
      - PERSISTANT_STORAGE_PATH=/wfs
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./local_wdb/wfs:/wfs
      - ./local_wdb/txlogs:/root/wdb/txlogs
      - ./local_wdb/configs:/root/wdb/configs
