version: '3.4'

services:
  wunderdb:
    image: wunderdb
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: wunderdb
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - PERSISTANT_STORAGE_PATH=/wfs
      - ADMIN_ID=${ADMIN_ID}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      # optional wdb-tools usage field - pass without quotes ("")
      - USE_TOOL=true
      - TOOL_INSTRUCTION=/tools/migrate_databases_primary_key
    volumes:
      - ./local_wdb/wfs:/wfs
      - ./local_wdb/txlogs:/root/wdb/txlogs
      - ./local_wdb/configs:/root/wdb/configs
