# fly.toml app configuration file generated for wunderdb on 2023-05-19T02:13:33+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wunderdb"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "hkg"

[build]

[env]
  PORT = "8080"
  ADDITIONAL_MESSAGE="BETA BUILD: wdb preview hosted on fly.io, might be unstable"

[experimental]
  auto_rollback = true

[[mounts]]
  destination = "/root"
  source = "wunderdb_volume"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
